#! /bin/bash
if [[ -z "$(ps aux | grep 'gitweb/webrick' | grep -v grep)" ]] ; then
	echo "starting git instaweb"
	git instaweb --httpd webrick
	sleep 1
	echo "opening firefox to http://localhost:1234"
	# firefox http://localhost:1234 & # instaweb opens automatically
else
	echo "git instaweb seems to be running already"
	echo "opening firefox to http://localhost:1234"
	firefox http://localhost:1234 &
fi
